service:
  http:
    port: :8080
  grpc:
    port: :9000

  websocket:
    write_wait: 10s
    pong_wait: 60s
    ping_period: 54s
    max_message_size: 512

  cors:
    allowOrigin: "http://localhost:8082"
    allowMethods: "POST,GET,OPTIONS,PUT,DELETE"
    allowHeaders: "Content-Type,X-Csrf-Token"
    allowCredentials: true
    exposeHeaders: "X-Csrf-Token"

auth:
  jwt:
    expire: 86400
    cookie:
      name: jwt-token
      maxAge: 86400
      secure: true
      httpOnly: true

mongo:
  driver: mongo

postgres:
  maxOpenConns: 60
  connMaxLifetime: 120
  maxIdleConns: 30
  connMaxIdleTime: 20
  driver: postgres

redis:
  db: 0
  poolSize: 50
  dialTimeout: 5s
  readTimeout: 3s
  writeTimeout: 3s
  poolTimeout: 4s

aws:
  useSSL: false
  avatarBucketName: "avatars"

websocket:
  writeWait: "10s"
  pongWait: "60s"
  pingPeriod: "54s"
  maxMessageSize: 512
  reconnect: true
  maxReconnect: 5
  reconnectDelay: "5s"       
